### PR TITLE
updated to match official

### PR DESCRIPTION
**Pull request by ethanclevenger91**
see https://github.com/vimeo/player-api/tree/master/javascript

I was having trouble with what was here, checked out the official and it _does_ work, so I updated this.

### CODE REVIEW

**Comment by austinpray** [comment]
thank you!

**Comment by ethanclevenger91** [comment]
Did you update the bower library as well?

**Comment by austinpray** [comment]
@ethanclevenger91 just tagged a new release as 1.0.0

**Comment by ethanclevenger91** [comment]
Excellent, thanks!

**Pull request merged**
